### ISSUE TITLE
Major Issue

### ISSUE THREAD

**Issue by OwenHobbs** [DdogN/drewblog#1]
I think I found a major issue. I see that you have an uppercase "V" in versus with no abbreviation period. It should be "AMD vs. Intel". I'll submit a pull request for this inconvenience.

**Comment by OwenHobbs** [comment]
The pull request is now open, merge them.

**Comment by DdogN** [comment]
Ok, i will fix this, i addewd more stuff and did not see them so i will not merge but thank you for helping out
